// ============================================================================
// КОНТАКТЫ — ПОМЕНЯЙ ЭТО НА СВОИ ДАННЫЕ
// ============================================================================

export const contacts = {
  brandName: "Hatyra",
  founderName: "—",
  phone: "+993 00 00-00-00",
  whatsapp: "99300000000",
  telegram: "hatyra_care",
  email: "hello@hatyra.com",
  city: { ru: "Туркменабад, Туркменистан", en: "Türkmenabat, Turkmenistan" },
} as const;

export type Locale = "ru" | "en";

export const content = {
  ru: {
    nav: {
      about: "О нас",
      howItWorks: "Как мы работаем",
      services: "Услуги",
      guarantee: "Гарантия",
      faq: "Вопросы",
      contact: "Связаться",
      cta: "Оставить заявку",
    },
    hero: {
      eyebrow: "Уход за могилами в Туркменистане",
      title: "Мы позаботимся о памяти тех,\nкто далеко от вас",
      subtitle:
        "Если родные похоронены в Туркменистане, а вы за тысячи километров — мы возьмём заботу о могиле на себя. Уборка, оформление, фото-отчёт — всё с уважением и вниманием к деталям.",
      ctaPrimary: "Оставить заявку",
      ctaSecondary: "Как это работает",
      trustLine: "Оплата только после фото- и видео-отчёта. Не понравилось — не платите.",
    },
    about: {
      eyebrow: "О нас",
      title: "Мы — местные.\nИ мы это понимаем",
      paragraphs: [
        "Hatyra — это сервис ухода за могилами в Туркменистане для людей, которые живут далеко: в России, Европе, Израиле, США. Мы знаем, каково это — быть не рядом, когда хочется навестить могилу родного человека.",
        "Мы основаны в Туркменабаде и работаем по всему региону. В будущем расширим географию на весь Туркменистан. Каждое наше посещение могилы заканчивается фото- и видео-отчётом — чтобы вы видели, как именно мы выполнили работу.",
        "Это не просто услуга. Это форма уважения — к ушедшим и к тем, кто помнит их, находясь вдали от дома.",
      ],
    },
    howItWorks: {
      eyebrow: "Как мы работаем",
      title: "Семь простых шагов",
      subtitle:
        "Прозрачный процесс без сюрпризов. Вы всегда знаете, что происходит, и не платите ни копейки до того, как увидите результат.",
      steps: [
        { title: "Оставляете заявку", text: "Заполняете форму на сайте или пишете нам в WhatsApp / Telegram. Расскажите, чьё захоронение и где находится." },
        { title: "Связываемся с вами", text: "Свяжемся в течение 24 часов, уточним детали: точное место, ваши пожелания, удобное время." },
        { title: "Едем на место", text: "Находим могилу, фотографируем её состояние «до» — без приукрашивания, как есть." },
        { title: "Согласуем работу и цену", text: "Присылаем вам фото и предложение по работам с конкретной ценой. Вы решаете, что делаем." },
        { title: "Выполняем работу", text: "Уборка, очистка памятника, прополка, замена цветов, покраска ограды — всё, о чём договорились." },
        { title: "Отправляем фото- и видео-отчёт", text: "Подробные фото «до» и «после», короткое видео обхода. Вы увидите каждую деталь." },
        { title: "Оплата — после отчёта", text: "Если результат вас устраивает — оплачиваете удобным способом. Не устроил — не платите." },
      ],
    },
    services: {
      eyebrow: "Что мы делаем",
      title: "Услуги под ваш запрос",
      subtitle: "Мы только начали работать, поэтому пока не делим услуги на жёсткие пакеты. Опишите, что нужно — мы оценим объём и предложим решение.",
      items: [
        { title: "Уборка и очистка", text: "Вынос мусора, удаление сорняков, мытьё памятника и плиты, протирка фотографий, очистка ограды." },
        { title: "Сезонный уход", text: "Регулярные посещения весной и осенью, а также к памятным датам — день рождения, годовщина, поминальные дни." },
        { title: "Оформление и реставрация", text: "Покраска ограды, реставрация букв, замена цветов, посадка растений, укладка камней или щебня." },
        { title: "Памятные даты", text: "Возложение цветов и наведение порядка к конкретной дате. Видео-отчёт в день события." },
        { title: "Поиск могилы", text: "Если вы давно не были и не помните точное место — поможем найти захоронение по доступным данным." },
        { title: "Сопровождение визита", text: "Если вы планируете приехать сами — поможем организовать всё на месте: дорогу, цветы, уборку перед визитом." },
      ],
      pricingNote: "Минимальный заказ — от 200 манат / от 60 $. Точную стоимость рассчитываем после осмотра.",
    },
    guarantee: {
      eyebrow: "Наша гарантия",
      title: "Сначала фото — потом оплата",
      paragraphs: [
        "Мы понимаем главный страх клиента: «А что если они возьмут деньги и ничего не сделают?» Поэтому мы убрали этот риск полностью.",
        "Вы не платите ни копейки до того, как получите от нас фото- и видео-отчёт о выполненной работе. Не понравился результат — не платите. Без объяснений и без споров.",
      ],
      perks: [
        { title: "Оплата по факту", text: "Только после того, как вы увидели результат и остались довольны." },
        { title: "Фото и видео каждой работы", text: "Подробные фото «до» и «после», видео обхода могилы." },
        { title: "Связь напрямую", text: "WhatsApp и Telegram — пишите в любое время, отвечаем в течение дня." },
        { title: "Скидка первым клиентам", text: "Первым 10 клиентам — скидка 30% в обмен на разрешение использовать фото работ на сайте." },
      ],
    },
    faq: {
      eyebrow: "Частые вопросы",
      title: "Что обычно спрашивают",
      items: [
        { q: "Как я узнаю, что вы действительно сделали работу, а не просто прислали фото из интернета?", a: "Мы присылаем фото с разных ракурсов и короткое видео обхода с указанием даты съёмки. На фото видно конкретное место, ограду, окружение — это нельзя подделать. Если хотите — можем сделать видеозвонок прямо с кладбища." },
        { q: "Я не помню точно, где находится могила. Сможете найти?", a: "Да. Назовите ФИО покойного, год рождения и смерти, кладбище или район — мы найдём. Если данных мало, поможем восстановить через архивы и местных смотрителей." },
        { q: "Как платить из-за границы?", a: "На старте принимаем оплату через банковский перевод, Western Union, Золотую Корону или USDT (криптовалюта). Со временем подключим карты Visa/Mastercard. Способ выбираем удобный для вас." },
        { q: "Какие у вас цены?", a: "Цена зависит от объёма работ. Минимальный заказ — от 200 манат (около 60 $). После осмотра присылаем точное предложение — и только тогда вы решаете, заказывать или нет." },
        { q: "Как часто можно заказывать уход?", a: "Можно разово, можно с регулярными визитами — например, 4 раза в год плюс к памятным датам. Расскажите, что хотите, и составим график." },
        { q: "В каких городах вы работаете?", a: "Сейчас — Туркменабад и окрестности. В планах — все регионы Туркменистана. Если ваш город ещё не в списке, напишите нам — мы постараемся помочь." },
      ],
    },
    contact: {
      eyebrow: "Связаться с нами",
      title: "Расскажите, что вам нужно",
      subtitle: "Опишите ситуацию — где похоронен ваш родной человек, что хотелось бы сделать. Свяжемся в течение 24 часов. Это бесплатно и ни к чему не обязывает.",
      labels: {
        name: "Ваше имя",
        contact: "Телефон или email",
        relativeName: "ФИО покойного (необязательно)",
        cemetery: "Город / кладбище",
        message: "Что нужно сделать",
        send: "Отправить",
        sending: "Отправляем...",
        success: "Спасибо! Заявка получена. Свяжемся с вами в течение 24 часов.",
        error: "Что-то пошло не так. Напишите нам напрямую в WhatsApp или Telegram.",
      },
      placeholders: {
        name: "Айгуль",
        contact: "email или телефон с кодом страны",
        relativeName: "Иванов Иван Иванович",
        cemetery: "Туркменабад, кладбище ...",
        message: "Хочу заказать уборку и фото-отчёт к 9 мая. Бабушка похоронена...",
      },
      contactHint: "Если укажете email — будем присылать уведомления о статусе на почту.",
      orWrite: "Или напишите нам напрямую:",
    },
    footer: {
      tagline: "Уход за могилами в Туркменистане. Для тех, кто далеко, но помнит.",
      rights: "Все права защищены",
    },
    me: {
      eyebrow: "Личный кабинет",
      title: "Мои заявки",
      subtitle: "Здесь сохраняется история всех ваших заявок. Заходите когда хотите проверить статус — авторизация по email, без паролей.",
      active: "Активные",
      archive: "Архив",
      newRequest: "Новая заявка",
      askQuestion: "Задать вопрос →",
      logout: "Выйти",
      newMessage: "Есть сообщение",
      statusLabels: {
        new: "Получена",
        in_progress: "В работе",
        done: "Выполнена",
        cancelled: "Отменена",
      },
    },
    login: {
      eyebrow: "Вход",
      title: "Войти в свой кабинет",
      subtitle: "Введите email, который вы указывали при отправке заявки. Мы пришлём ссылку для входа — без паролей и без регистрации.",
      emailLabel: "Ваш email",
      emailPlaceholder: "anna@example.com",
      submit: "Получить ссылку",
      sending: "Отправляем...",
      successTitle: "Проверьте почту",
      successText: "Если по этому email есть заявки, мы только что отправили письмо со ссылкой для входа. Ссылка действует 30 минут.",
      hint: "Войти можно только если вы уже отправляли заявку с этого email.",
      errors: {
        missing: "Введите email",
        invalid: "Похоже, это не email — проверьте написание",
        server: "Что-то пошло не так. Попробуйте ещё раз.",
      },
      backToHome: "Вернуться на сайт",
    },
    find: {
      eyebrow: "Восстановление ссылок",
      title: "Найти мои заявки",
      subtitle: "Введите email, который вы указывали при отправке заявки. Мы пришлём на него письмо со всеми вашими ссылками отслеживания.",
      emailLabel: "Ваш email",
      emailPlaceholder: "anna@example.com",
      submit: "Отправить письмо",
      sending: "Отправляем...",
      successTitle: "Проверьте почту",
      successText: "Если по этому адресу есть заявки, мы только что отправили письмо со ссылками. Не пришло — проверьте папку «Спам» и убедитесь, что email указан правильно.",
      errors: {
        missing: "Введите email",
        invalid: "Похоже, это не email — проверьте написание",
        server: "Что-то пошло не так. Попробуйте ещё раз.",
      },
      backToHome: "Вернуться на сайт",
    },
    recovery: {
      banner: "Вы уже отправляли заявку",
      bannerCta: "Открыть",
      multiple: "У вас активных заявок:",
      lostLink: "Потеряли ссылку?",
      findByEmail: "Найти по email",
    },
    track: {
      eyebrow: "Отслеживание заявки",
      title: "Спасибо! Заявка получена",
      saveLink: "Сохраните эту ссылку — здесь вы будете видеть статус вашей заявки.",
      copy: "Скопировать ссылку",
      copied: "Скопировано",
      number: "Номер заявки",
      submitted: "Отправлена",
      lastUpdate: "Последнее обновление",
      status: "Статус",
      messageFromUs: "Сообщение от нас",
      noMessageYet: "Пока новых сообщений от нас нет",
      yourRequest: "Ваша заявка",
      whatYouAsked: "Что вы попросили",
      cemetery: "Кладбище",
      relativeName: "Покойный",
      contactUs: "Связаться с нами",
      checkAgain: "Обновить",
      backToHome: "Вернуться на сайт",
      statusLabels: {
        new: "Получена — ждёт обработки",
        in_progress: "Принята в работу",
        done: "Выполнена",
        cancelled: "Отменена",
      },
      statusDescriptions: {
        new: "Мы получили вашу заявку. Свяжемся с вами в течение 24 часов.",
        in_progress: "Мы взяли вашу заявку в работу. Скоро отправим фото-отчёт.",
        done: "Работа выполнена. Если у вас остались вопросы — напишите нам.",
        cancelled: "К сожалению, мы не смогли выполнить эту заявку. Подробности — в сообщении ниже.",
      },
    },
  },
  en: {
    nav: {
      about: "About",
      howItWorks: "How it works",
      services: "Services",
      guarantee: "Guarantee",
      faq: "FAQ",
      contact: "Contact",
      cta: "Request a service",
    },
    hero: {
      eyebrow: "Grave care in Turkmenistan",
      title: "We care for the memory\nof those far from you",
      subtitle: "If your loved ones are buried in Turkmenistan and you live thousands of miles away — we will take care of the grave for you. Cleaning, decoration, full photo report — done with respect and attention to detail.",
      ctaPrimary: "Request a service",
      ctaSecondary: "How it works",
      trustLine: "You only pay after you receive the photo and video report. Not happy — don't pay.",
    },
    about: {
      eyebrow: "About us",
      title: "We are local.\nAnd we understand",
      paragraphs: [
        "Hatyra is a grave care service in Turkmenistan for people living abroad — in Russia, Europe, Israel, the USA. We know how it feels to be far from home when you wish to visit a loved one's grave.",
        "We are based in Türkmenabat and work across the region. We plan to expand across all of Turkmenistan. Every visit ends with a detailed photo and video report so you can see exactly how the work was done.",
        "This is not just a service. It is a form of respect — for those who passed and for those who still remember them from far away.",
      ],
    },
    howItWorks: {
      eyebrow: "How we work",
      title: "Seven simple steps",
      subtitle: "A transparent process with no surprises. You always know what is happening, and you don't pay a cent until you see the result.",
      steps: [
        { title: "You send a request", text: "Fill in the form on the site or message us via WhatsApp or Telegram. Tell us whose grave and where it is." },
        { title: "We get back to you", text: "We reply within 24 hours and clarify the details: exact location, your wishes, a convenient time." },
        { title: "We visit the site", text: "We find the grave and photograph its current state — honestly, exactly as it is." },
        { title: "We agree on the work and price", text: "We send you the photos and a proposal with a clear price. You decide what to do." },
        { title: "We do the work", text: "Cleaning, washing the monument, weeding, replacing flowers, painting the fence — everything we agreed on." },
        { title: "We send a photo and video report", text: "Detailed before/after photos and a short video walk-around. You see every detail." },
        { title: "You pay — after the report", text: "If you are happy with the result — pay any way that's convenient for you. If not — don't pay." },
      ],
    },
    services: {
      eyebrow: "What we do",
      title: "Services tailored to you",
      subtitle: "We are just starting out, so we don't lock services into rigid packages. Tell us what you need — we will assess and offer a solution.",
      items: [
        { title: "Cleaning", text: "Removing waste and weeds, washing the monument, polishing the photo, cleaning the fence." },
        { title: "Seasonal care", text: "Regular visits in spring and autumn, plus visits on memorial dates — birthdays, anniversaries, religious holidays." },
        { title: "Decoration and restoration", text: "Repainting the fence, restoring engravings, replacing flowers, planting greenery, laying stones." },
        { title: "Memorial dates", text: "Laying flowers and tidying up for a specific date. Same-day video report." },
        { title: "Locating a grave", text: "If you haven't visited in a long time and don't remember the exact spot — we will help locate it." },
        { title: "Visit support", text: "If you plan to come in person — we'll prepare everything on site: route, flowers, cleaning before your arrival." },
      ],
      pricingNote: "Minimum order from 200 TMT / from $60. We provide an exact quote after the on-site visit.",
    },
    guarantee: {
      eyebrow: "Our guarantee",
      title: "Photos first — payment later",
      paragraphs: [
        "We understand the main fear: \"What if they take the money and do nothing?\" So we removed that risk completely.",
        "You don't pay a cent until you receive a photo and video report of the completed work. Not satisfied — don't pay. No questions asked.",
      ],
      perks: [
        { title: "Pay after the result", text: "Only once you've seen the work and are happy with it." },
        { title: "Photo and video for every job", text: "Detailed before/after shots and a short walk-around video." },
        { title: "Direct contact", text: "WhatsApp and Telegram — message us anytime, we reply within the day." },
        { title: "Discount for first clients", text: "First 10 clients get 30% off in exchange for permission to use photos of the work on the site." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "What people usually ask",
      items: [
        { q: "How do I know you actually did the work and didn't just send some random photos?", a: "We send photos from multiple angles and a short walk-around video with the date visible. The fence, surroundings, and exact spot are visible — that can't be faked. If you wish, we can also do a video call live from the cemetery." },
        { q: "I don't remember the exact location of the grave. Can you find it?", a: "Yes. Provide the deceased's full name, year of birth and death, cemetery or district — we'll find it. If the data is limited, we'll help reconstruct it through archives and local caretakers." },
        { q: "How can I pay from abroad?", a: "We currently accept bank transfers, Western Union, Zolotaya Korona, and USDT (crypto). We're working on adding Visa/Mastercard. We'll choose what's most convenient for you." },
        { q: "What are your prices?", a: "It depends on the scope. Minimum order from 200 TMT (around $60). After the on-site assessment we send you an exact quote — only then do you decide whether to proceed." },
        { q: "How often can I order grave care?", a: "One-off or regular — for example, four visits a year plus memorial dates. Tell us your needs and we'll build a schedule." },
        { q: "Which cities do you cover?", a: "Currently Türkmenabat and surrounding areas. We plan to cover all regions of Turkmenistan. If your city isn't on the list yet — message us, we'll do our best." },
      ],
    },
    contact: {
      eyebrow: "Contact us",
      title: "Tell us what you need",
      subtitle: "Describe your situation — where your loved one is buried, what you'd like done. We respond within 24 hours. It's free and no commitment.",
      labels: {
        name: "Your name",
        contact: "Phone or email",
        relativeName: "Deceased's full name (optional)",
        cemetery: "City / cemetery",
        message: "What needs to be done",
        send: "Send",
        sending: "Sending...",
        success: "Thank you! Your request was received. We'll be in touch within 24 hours.",
        error: "Something went wrong. Please contact us directly via WhatsApp or Telegram.",
      },
      placeholders: {
        name: "Aigul",
        contact: "email or phone with country code",
        relativeName: "John Doe",
        cemetery: "Türkmenabat, ... cemetery",
        message: "I'd like a cleaning and photo report by May 9. My grandmother is buried...",
      },
      contactHint: "If you provide an email — we'll send status update notifications.",
      orWrite: "Or message us directly:",
    },
    footer: {
      tagline: "Grave care in Turkmenistan. For those who are far away but still remember.",
      rights: "All rights reserved",
    },
    me: {
      eyebrow: "My account",
      title: "My requests",
      subtitle: "All your requests in one place. Come back anytime to check status — email-based access, no passwords.",
      active: "Active",
      archive: "Archive",
      newRequest: "New request",
      askQuestion: "Ask a question →",
      logout: "Log out",
      newMessage: "New message",
      statusLabels: {
        new: "Received",
        in_progress: "In progress",
        done: "Completed",
        cancelled: "Cancelled",
      },
    },
    login: {
      eyebrow: "Sign in",
      title: "Access your account",
      subtitle: "Enter the email you used when submitting a request. We'll send you a sign-in link — no passwords, no registration.",
      emailLabel: "Your email",
      emailPlaceholder: "anna@example.com",
      submit: "Send sign-in link",
      sending: "Sending...",
      successTitle: "Check your inbox",
      successText: "If there are requests for this email, we just sent a sign-in link. It's valid for 30 minutes.",
      hint: "You can only sign in if you've already submitted a request with this email.",
      errors: {
        missing: "Please enter an email",
        invalid: "This doesn't look like an email — please check",
        server: "Something went wrong. Please try again.",
      },
      backToHome: "Back to site",
    },
    find: {
      eyebrow: "Recover links",
      title: "Find my requests",
      subtitle: "Enter the email you used when submitting your request. We'll email you all your tracking links.",
      emailLabel: "Your email",
      emailPlaceholder: "anna@example.com",
      submit: "Send email",
      sending: "Sending...",
      successTitle: "Check your inbox",
      successText: "If there are any requests for this email, we've just sent you a message with the links. If you don't see it, check your spam folder and verify the email.",
      errors: {
        missing: "Please enter an email",
        invalid: "This doesn't look like an email — please check",
        server: "Something went wrong. Please try again.",
      },
      backToHome: "Back to site",
    },
    recovery: {
      banner: "You have an active request",
      bannerCta: "Open",
      multiple: "Active requests:",
      lostLink: "Lost your link?",
      findByEmail: "Find by email",
    },
    track: {
      eyebrow: "Request tracking",
      title: "Thank you! We've received your request",
      saveLink: "Save this link — this is where you'll see the status of your request.",
      copy: "Copy link",
      copied: "Copied",
      number: "Request number",
      submitted: "Submitted",
      lastUpdate: "Last update",
      status: "Status",
      messageFromUs: "Message from us",
      noMessageYet: "No new messages from us yet",
      yourRequest: "Your request",
      whatYouAsked: "What you asked for",
      cemetery: "Cemetery",
      relativeName: "Deceased",
      contactUs: "Contact us",
      checkAgain: "Refresh",
      backToHome: "Back to site",
      statusLabels: {
        new: "Received — pending",
        in_progress: "In progress",
        done: "Completed",
        cancelled: "Cancelled",
      },
      statusDescriptions: {
        new: "We've received your request. We'll be in touch within 24 hours.",
        in_progress: "We've started working on your request. The photo report will follow soon.",
        done: "The work is completed. If you have any questions — message us anytime.",
        cancelled: "Unfortunately we couldn't fulfil this request. See the message below for details.",
      },
    },
  },
} as const;

export type Translation = (typeof content)[Locale];
